kind: pipeline
type: docker
name: build

steps:
  - name: build application
    image: docker:19.03.12
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    environment:
      SHOPIFY_CLIENT_ID:
        from_secret: SHOPIFY_CLIENT_ID
      SHOPIFY_CLIENT_SECRET:
        from_secret: SHOPIFY_CLIENT_SECRET
      SHOPIFY_REDIRECT_URI:
        from_secret: SHOPIFY_REDIRECT_URI
      SHOPIFY_SHOP_DOMAIN:
        from_secret: SHOPIFY_SHOP_DOMAIN
      SHOPIFY_AUTH_ENDPOINT:
        from_secret: SHOPIFY_AUTH_ENDPOINT
      SHOPIFY_TOKEN_ENDPOINT:
        from_secret: SHOPIFY_TOKEN_ENDPOINT
      SHOPIFY_USERINFO_ENDPOINT:
        from_secret: SHOPIFY_USERINFO_ENDPOINT
      SHOPIFY_JWKS_URI:
        from_secret: SHOPIFY_JWKS_URI
      SHOPIFY_SCOPES:
        from_secret: SHOPIFY_SCOPES
      SHOPIFY_WEBHOOK_SECRET:
        from_secret: SHOPIFY_WEBHOOK_SECRET
    commands:
      - echo "Starting build application step..."
      - export APP_ENV=stage
      - if [ "${DRONE_BRANCH}" = "main" ]; then export APP_ENV=main; fi
      - echo "Building Docker image with APP_ENV=${APP_ENV}..."
      - chmod +x build.sh
      - ./build.sh
clone:
  depth: 1

trigger:
  branch:
    - sprint-*
    - main
  event:
    - push

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

node:
  machine: personal-ci
  command: nl

---
kind: pipeline
type: docker
name: test
depends_on:
  - build

steps:
  - name: test application
    image: docker:19.03.12
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    environment:
      SHOPIFY_CLIENT_ID:
        from_secret: SHOPIFY_CLIENT_ID_TEST
      SHOPIFY_CLIENT_SECRET:
        from_secret: SHOPIFY_CLIENT_SECRET_TEST
      SHOPIFY_REDIRECT_URI:
        from_secret: SHOPIFY_REDIRECT_URI_TEST
      SHOPIFY_SHOP_DOMAIN:
        from_secret: SHOPIFY_SHOP_DOMAIN_TEST
      SHOPIFY_AUTH_ENDPOINT:
        from_secret: SHOPIFY_AUTH_ENDPOINT_TEST
      SHOPIFY_TOKEN_ENDPOINT:
        from_secret: SHOPIFY_TOKEN_ENDPOINT_TEST
      SHOPIFY_USERINFO_ENDPOINT:
        from_secret: SHOPIFY_USERINFO_ENDPOINT_TEST
      SHOPIFY_JWKS_URI:
        from_secret: SHOPIFY_JWKS_URI_TEST
      SHOPIFY_SCOPES:
        from_secret: SHOPIFY_SCOPES_TEST
      SHOPIFY_WEBHOOK_SECRET:
        from_secret: SHOPIFY_WEBHOOK_SECRET_TEST
    commands:
      - echo "Starting test application step..."
      - export APP_ENV=testing
      - export TEST_MODE=true
      - |
        docker run --rm \
        -e SHOPIFY_CLIENT_ID \
        -e SHOPIFY_CLIENT_SECRET \
        -e SHOPIFY_REDIRECT_URI \
        -e SHOPIFY_SHOP_DOMAIN \
        -e SHOPIFY_AUTH_ENDPOINT \
        -e SHOPIFY_TOKEN_ENDPOINT \
        -e SHOPIFY_USERINFO_ENDPOINT \
        -e SHOPIFY_JWKS_URI \
        -e SHOPIFY_SCOPES \
        -e SHOPIFY_WEBHOOK_SECRET \
        shopify-oidc:${DRONE_COMMIT_SHA} sh -c "cd /var/www && php artisan test"

trigger:
  branch:
    - sprint-*
    - main
  event:
    - push

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
node:
  machine: personal-ci
  command: nl

---
kind: pipeline
type: docker
name: deploy-development

depends_on:
  - test

steps:
  - name: deploy application
    image: docker:19.03.12
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    environment:
      DB_PASSWORD:
        from_secret: SPRINT_DB_PASSWORD
      SHOPIFY_CLIENT_ID:
        from_secret: SHOPIFY_CLIENT_ID_DEV
      SHOPIFY_CLIENT_SECRET:
        from_secret: SHOPIFY_CLIENT_SECRET_DEV
      SHOPIFY_REDIRECT_URI:
        from_secret: SHOPIFY_REDIRECT_URI_DEV
      SHOPIFY_SHOP_DOMAIN:
        from_secret: SHOPIFY_SHOP_DOMAIN_DEV
      SHOPIFY_AUTH_ENDPOINT:
        from_secret: SHOPIFY_AUTH_ENDPOINT_DEV
      SHOPIFY_TOKEN_ENDPOINT:
        from_secret: SHOPIFY_TOKEN_ENDPOINT_DEV
      SHOPIFY_USERINFO_ENDPOINT:
        from_secret: SHOPIFY_USERINFO_ENDPOINT_DEV
      SHOPIFY_JWKS_URI:
        from_secret: SHOPIFY_JWKS_URI_DEV
      SHOPIFY_SCOPES:
        from_secret: SHOPIFY_SCOPES_DEV
      SHOPIFY_WEBHOOK_SECRET:
        from_secret: SHOPIFY_WEBHOOK_SECRET_DEV
    commands:
      - echo "Starting deploy application step..."
      - chmod +x deploy.sh
      - ./deploy.sh
      - echo "Deploy application step completed."

trigger:
  branch:
    - sprint-*

  event:
    - push

node:
  machine: personal-ci
  command: nl

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: deploy-production

depends_on:
  - test

steps:
  - name: deploy application
    image: docker:19.03.12
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    environment:
      DB_PASSWORD:
        from_secret: DB_PASSWORD
      SHOPIFY_CLIENT_ID:
        from_secret: SHOPIFY_CLIENT_ID_PROD
      SHOPIFY_CLIENT_SECRET:
        from_secret: SHOPIFY_CLIENT_SECRET_PROD
      SHOPIFY_REDIRECT_URI:
        from_secret: SHOPIFY_REDIRECT_URI_PROD
      SHOPIFY_SHOP_DOMAIN:
        from_secret: SHOPIFY_SHOP_DOMAIN_PROD
      SHOPIFY_AUTH_ENDPOINT:
        from_secret: SHOPIFY_AUTH_ENDPOINT_PROD
      SHOPIFY_TOKEN_ENDPOINT:
        from_secret: SHOPIFY_TOKEN_ENDPOINT_PROD
      SHOPIFY_USERINFO_ENDPOINT:
        from_secret: SHOPIFY_USERINFO_ENDPOINT_PROD
      SHOPIFY_JWKS_URI:
        from_secret: SHOPIFY_JWKS_URI_PROD
      SHOPIFY_SCOPES:
        from_secret: SHOPIFY_SCOPES_PROD
      SHOPIFY_WEBHOOK_SECRET:
        from_secret: SHOPIFY_WEBHOOK_SECRET_PROD
    commands:
      - echo "Starting deploy application step..."
      - chmod +x ./production.sh
      - ./production.sh
      - echo "Deploy application step completed."
trigger:
  branch:
    - main
  event:
    - push

node:
  machine: personal-ci
  command: nl

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: deploy-production-main

steps:
  - name: deploy application
    image: docker:19.03.12
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    environment:
      DB_PASSWORD:
        from_secret: DB_PASSWORD
      SHOPIFY_CLIENT_ID:
        from_secret: SHOPIFY_CLIENT_ID_PROD
      SHOPIFY_CLIENT_SECRET:
        from_secret: SHOPIFY_CLIENT_SECRET_PROD
      SHOPIFY_REDIRECT_URI:
        from_secret: SHOPIFY_REDIRECT_URI_PROD
      SHOPIFY_SHOP_DOMAIN:
        from_secret: SHOPIFY_SHOP_DOMAIN_PROD
      SHOPIFY_AUTH_ENDPOINT:
        from_secret: SHOPIFY_AUTH_ENDPOINT_PROD
      SHOPIFY_TOKEN_ENDPOINT:
        from_secret: SHOPIFY_TOKEN_ENDPOINT_PROD
      SHOPIFY_USERINFO_ENDPOINT:
        from_secret: SHOPIFY_USERINFO_ENDPOINT_PROD
      SHOPIFY_JWKS_URI:
        from_secret: SHOPIFY_JWKS_URI_PROD
      SHOPIFY_SCOPES:
        from_secret: SHOPIFY_SCOPES_PROD
      SHOPIFY_WEBHOOK_SECRET:
        from_secret: SHOPIFY_WEBHOOK_SECRET_PROD
    commands:
      - echo "Starting deploy application step..."
      - chmod +x ./production.sh
      - ./production.sh
      - echo "Deploy application step completed."
trigger:
  branch:
    - main
  event:
    - promote
  target:
    - production

node:
  machine: personal-ci
  command: nl

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
